travis:
  secure:
    BINSTAR_TOKEN: fcnbvqbxLQA4mMxan2yOFZ/dDCFy3Y+IDZFhPxBg6P6Jm/+pp+hKOkQmkhVtpao+l/ULkB9upSSX2zLjINg7kLfEBdwYpyBbEumCoAlRY6N9yZ44F3EI1iUnk6tkc/yK+5BkLKTBLyrirApClV+LoUovBlJUsIourIX7RlfaZvfa1KtWn3XNUsLcB6GbnSl4vqK4KYfWp5XS3b5Z77lg86WFy61DY8PQqfLo2YISiGBI7nO4wik/3PTwQ7enMrBIt1tE6jgTwMAKSV6D6BT/AjJ6QDTq8ogm0wN6RthZWITBp6qfjFxhalCJxXqGi0v7siq+PgPKcshengbr7Nc/33CKpj1QAGI1kqgvs090Oo9srA6REoSmeWB9q4Jcl9FUTjli5UbOj2GHN92Tfhsx0wKmGjU91eS9ZN4dl4rqt1+Yj+zeoaXQMEM5XhZm9nr6dL6xv6dVuSzDlhMVgZWQXfwo5UoAEwzqh6K2b3jiENoO2wzRjRr+rGciUnZCzzjxwNDUjgmQi99Zya85ph2oDw0z1ELZPhqnZaGkwPgh8lfGpT3jW//t+p/qKxb2aOrHS30zyasyOtdCykulmttpd2jT8p6XScy/bp0UMicWN6ng7KoT1ojEIqC0IcDWqnQybMahRobJ+tMrcej/ng9gPv7WBHtHhxMRM6q8Vy6CxmQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
